# run specs
SEED: 42
NAME: "crosstransformer" # model name
RUN_NAME: "crosstransformer-contrastive-baseline" # unique run_name
# seed

# hyperparams
LR: 3e-4
EPOCHS: 300
BATCH_SIZE: 8

# model config
DROPOUT: 0.1
NUM_LAYERS: 2
NUM_HEADS: 4
HIDDEN_SIZE: 256 # 64 * 4
CONTRASTIVE: True